version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: productmanagement-db
    environment:
      POSTGRES_DB: productmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - productmanagement-network

  # .NET API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productmanagement-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DATABASE_CONNECTION_STRING=Host=postgres;Database=productmanagement;Username=postgres;Password=password123
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - postgres
    networks:
      - productmanagement-network

volumes:
  postgres_data:

networks:
  productmanagement-network:
    driver: bridge
